EventManagement/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from django.views.generic import TemplateView

from EventManagement import views
urlpatterns = [
    path('', views.index, name="index"),
    path('admin_panel', views.admin_panel, name="admin_panel"),
    path('add/profile',views.add_profile, name="add_profile"),
    path('add/profile/success', TemplateView.as_view(template_name='EventManagement/profile_add_sucess.html'), name="add_profile_success"),
    path('update/event/<slug:event_code>', views.UpdateEvent.as_view(), name="update_event"),
    path('update/workshop/<slug:event_code>', views.UpdateWorkshop.as_view(), name="update_workshop"),
    path('login', auth_views.login,{'template_name':'EventManagement/login.html'}, name="login"),
    path('logout', auth_views.logout, name="logout"),


    path('api/get/event/data', views.get_event_data, name="get_event_data"),
    path('api/get/user/data', views.get_user_data, name="get_user_data"),
]

RituEventManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EventManagement.urls'))
]

EventManagement/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, Group
from django.db import models


# Create your models here.
from django.db.models import Max


class Profile(models.Model):
    name = models.CharField(max_length=500)
    email = models.EmailField()
    phone = models.CharField(max_length=15, unique=True)
    college = models.CharField(max_length=500)
    id_code = models.CharField(max_length=250)

    def save(self, *args,**kwargs):
        code = Profile.objects.all().aggregate(Max('id'))['id__max']
        self.id_code = "RITU" + str(code if code is not None else "00")
        return super(Profile,self).save()

    @property
    def serialize(self):
        return {
            'name':self.name,
            'email':self.email,
            'phone':self.phone,
            'college':self.college,
            'id_code':self.id_code
        }

    def __str__(self):
        return self.name


class Volunteer(models.Model):
    GROUP_NAME = "volunteer"
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)

    def __str__(self):
        return self.user.username

    @staticmethod
    def create(username, first_name, last_name, email, phone, password, group_name=GROUP_NAME):
        user = User(username=username, first_name=first_name, last_name=last_name, email=email)
        user.password = make_password(password)
        user.save()
        user.groups.add(Group.objects.filter(name=group_name).first())
        v = Volunteer(user=user, phone=phone)
        v.save()
        return v


class EventVolunteer(Volunteer):
    GROUP_NAME = "event_volunteer"
    organizer = models.ForeignKey('Organizer', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    @classmethod
    def create(cls, username, first_name, last_name, email, phone, password, organizer):
        user = User(username=username, first_name=first_name, last_name=last_name, email=email)
        user.password = make_password(password)
        user.save()
        user.groups.add(Group.objects.filter(name=EventVolunteer.GROUP_NAME).first())
        v = cls(user=user, phone=phone)
        v.organizer = organizer
        v.save()


class RituAdmin(Volunteer):
    GROUP_NAME = "admin_"

    class Meta:
        proxy = True

    def __str__(self):
        return self.user.username

    @classmethod
    def create(cls, username, first_name, last_name, email, phone, password):
        r = Volunteer.create(username, first_name, last_name, email, phone, cls.GROUP_NAME)


class RegistrationDesk(Volunteer):
    GROUP_NAME = "registration_desk"

    class Meta:
        proxy = True

    def __str__(self):
        return self.user.username

    @classmethod
    def create(cls, username, first_name, last_name, email, phone, password):
        r = Volunteer.create(username, first_name, last_name, email, phone, password, cls.GROUP_NAME)


# class Head(Volunteer):
#     GROUP_NAME = "dept_head"
#
#     class Meta:
#         proxy = True
#
#     def __str__(self):
#         return self.user.username
#
#     @classmethod
#     def create(cls, username, first_name, last_name, email, phone, password):
#         r = Volunteer.create(username, first_name, last_name, email, phone, cls.GROUP_NAME)


class Organizer(models.Model):
    name = models.CharField(max_length=255)
    # head = models.OneToOneField(Head, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=10, unique=True)
    organizer = models.ForeignKey(Organizer, on_delete=models.CASCADE)
    timing = models.CharField(max_length=250,null=True)
    additional_data = models.TextField(null=True)
    amount = models.CharField(max_length=10, null=True)
    is_team_event = models.BooleanField(default=False)
    venue = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Workshop(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=10)
    organizer = models.ForeignKey(Organizer, on_delete=models.CASCADE, null=True)
    timing = models.DateTimeField(null=True)
    amount = models.CharField(max_length=10, null=True)
    is_team_event = models.BooleanField(default=False)
    venue = models.CharField(max_length=500)


    def __str__(self):
        return self.name


class WorkshopRegistration(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)
    additional_data = models.TextField(null=True)
    registrar = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = (('profile', 'workshop'),)

    def __str__(self):
        return str(self.profile) + " | " + str(self.workshop) + ( " | " + self.additional_data if self.additional_data is not None else "")

class Registration(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    additional_data = models.TextField(null=True)
    registrar = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = (('profile', 'event'),)

    def __str__(self):
        return str(self.profile) + " | " + str(self.event) + ( " | " + self.additional_data if self.additional_data is not None else "")

EventManagement/forms.py
from django import forms

from EventManagement.models import Profile, Event, Workshop


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['id_code']


class EventForm(forms.ModelForm):
    additional_data = forms.CharField(required=False)

    class Meta:
        model = Event
        fields = ['additional_data', 'timing', 'venue']

class WorkshopForm(forms.ModelForm):
    additional_data = forms.CharField(required=False)

    class Meta:
        model = Workshop
        fields = ['additional_data', 'timing', 'venue']

EventManagement/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.views import View
from django.views.decorators.http import require_http_methods

from EventManagement.celery import send_email
from EventManagement.forms import ProfileForm, EventForm, WorkshopForm
from EventManagement.utils import belongs_to_group, group_login_required
from EventManagement.models import *


def index(request):
    if request.user.is_authenticated:
        return redirect('admin_panel')
    return render(request, 'EventManagement/login.html')


def logout_user(request):
    logout(request)
    return redirect('index')


@login_required
def admin_panel(request):
    context = {'event_list': Event.objects.all(), 'workshop_list': Workshop.objects.all(), 'user': request.user}
    if belongs_to_group(request.user, EventVolunteer.GROUP_NAME):
        event_volunteer = EventVolunteer.objects.get(user=request.user)
        context['event_volunteer'] = event_volunteer
        org_events = Event.objects.filter(organizer=event_volunteer.organizer)
        context['event_registrations'] = []
        for i, event in enumerate(org_events):
            context['event_registrations'].append({
                'code': event.code,
                'name': event.name,
                'list': []
            })
            registrations = Registration.objects.filter(event=event)
            for reg in registrations:
                context['event_registrations'][i]['list'].append({
                    'profile': reg.profile.serialize,
                    'additional_data': reg.additional_data,
                })
        org_workshops = Workshop.objects.filter(organizer=event_volunteer.organizer)
        context['workshop_registrations'] = []
        for i, event in enumerate(org_workshops):
            context['workshop_registrations'].append({
                'code': event.code,
                'name': event.name,
                'list': []
            })
            registrations = WorkshopRegistration.objects.filter(workshop=event)
            for reg in registrations:
                context['workshop_registrations'][i]['list'].append({
                    'profile': reg.profile.serialize,
                    'additional_data': reg.additional_data,
                })
        return render(request, 'EventManagement/event_volunteer.html', context)
    elif belongs_to_group(request.user, RegistrationDesk.GROUP_NAME):
        event_volunteer = RegistrationDesk.objects.get(user=request.user)
        context['event_volunteer'] = event_volunteer
        context['p_form'] = ProfileForm()
        id_code = request.session.get('id_code', None)
        print(id_code)
        if id_code is not None:
            del request.session['id_code']
        context['id_code'] = id_code
        return render(request, 'EventManagement/registration_admin.html', context)
    elif belongs_to_group(request.user, RituAdmin.GROUP_NAME):
        context['admin'] = RituAdmin.objects.get(user=request.user)
        org_events = Event.objects.all()
        context['event_registrations'] = []
        for i, event in enumerate(org_events):
            context['event_registrations'].append({
                'code': event.code,
                'name': event.name,
                'list': []
            })
            registrations = Registration.objects.filter(event=event)
            for reg in registrations:
                context['event_registrations'][i]['list'].append({
                    'profile': reg.profile.serialize,
                    'additional_data': reg.additional_data,
                })
        org_workshops = Workshop.objects.all()
        context['workshop_registrations'] = []
        for i, event in enumerate(org_workshops):
            context['workshop_registrations'].append({
                'code': event.code,
                'name': event.name,
                'list': []
            })
            registrations = WorkshopRegistration.objects.filter(workshop=event)
            for reg in registrations:
                context['workshop_registrations'][i]['list'].append({
                    'profile': reg.profile.serialize,
                    'additional_data': reg.additional_data,
                })
        return render(request, "EventManagement/ritu_admin_admin.html", context)
    else:
        raise PermissionDenied("Not a authorized to view the page")


@require_http_methods(["POST"])
@group_login_required(group_name=RegistrationDesk.GROUP_NAME)
def add_profile(request):
    print('')
    form = ProfileForm(request.POST)
    addition_info = request.POST["additional_info"]
    context = {'event_list': [], 'workshop_list': []}
    if Profile.objects.filter(phone=form.data['phone']).exists():
        profile = Profile.objects.filter(phone=form.data['phone']).first()
        events = Event.objects.all()
        for event in events:
            if event.code in request.POST:
                r = Registration()
                r.event = event
                r.registrar = request.user
                r.profile = profile
                r.additional_data = addition_info
                try:
                    r.save()
                except IntegrityError:
                    pass
                context['event_list'].append(event.name)
        workshops = Workshop.objects.all()
        for workshop in workshops:
            if workshop.code in request.POST:
                r = WorkshopRegistration()
                r.workshop = workshop
                r.registrar = request.user
                r.profile = profile
                r.additional_data = addition_info
                try:
                    r.save()
                except IntegrityError:
                    pass
                context['workshop_list'].append(workshop.name)
        request.session['id_code'] = profile.id_code
        return redirect('admin_panel')
    if form.is_valid():
        profile = form.save()
        events = Event.objects.all()
        for event in events:
            if event.code in request.POST:
                r = Registration()
                r.event = event
                r.registrar = request.user
                r.profile = profile
                r.additional_data = addition_info
                r.save()
                context['event_list'].append(event.name)
        workshops = Workshop.objects.all()
        for workshop in workshops:
            if workshop.code in request.POST:
                r = WorkshopRegistration()
                r.workshop = workshop
                r.registrar = request.user
                r.profile = profile
                r.additional_data = addition_info
                r.save()
                context['workshop_list'].append(workshop.name)
        send_email.delay(profile.serialize, context)
        request.session['id_code'] = profile.id_code
        return redirect('admin_panel')
    return render(request, "EventManagement/registration_admin.html", {'p_form': form,
                                                                       'id_code':None,
                                                                       'name': form.data['name'],
                                                                       'phone': form.data['phone'],
                                                                       'college': form.data['college'],
                                                                       'email': form.data['email'],
                                                                       'additional_info': addition_info,
                                                                       'event_list': Event.objects.all(),
                                                                       'workshop_list': Workshop.objects.all()})


class UpdateEvent(View):
    def get(self, request, event_code):
        if not belongs_to_group(request.user, EventVolunteer.GROUP_NAME):
            raise PermissionDenied()
        event_v = EventVolunteer.objects.get(user=request.user)
        event = get_object_or_404(Event, code=event_code)
        if event.organizer != event_v.organizer:
            raise PermissionDenied()
        form = EventForm(instance=event)
        return render(request, 'EventManagement/update_event.html', {'form': form,
                                                                     'user': request.user,
                                                                     'event': event,
                                                                     'slug': event_code})

    def post(self, request, event_code):
        if not belongs_to_group(request.user, EventVolunteer.GROUP_NAME):
            raise PermissionDenied()
        event = get_object_or_404(Event, code=event_code)
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('index')
        return render(request, 'EventManagement/update_event.html', {'form': form, 'user': request.user,
                                                                     'event': event,
                                                                     'slug': event_code})


class UpdateWorkshop(View):
    def get(self, request, event_code):
        if not belongs_to_group(request.user, EventVolunteer.GROUP_NAME):
            raise PermissionDenied()
        event_v = EventVolunteer.objects.get(user=request.user)
        event = get_object_or_404(Workshop, code=event_code)
        if event.organizer != event_v.organizer:
            raise PermissionDenied()
        form = WorkshopForm(instance=event)

EventManagement/templates/EventManagement/event_volunteer_admin.html
{% extends 'EventManagement/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'event_volunteer_admin.css' %}">
{% endblock %}
{% block nav-icons %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link event-info" href="#">Event Info <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item  active">
                <a class="nav-link form-submit" href="#">Form submit</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Welcome {{ event_volunteer.user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
        </ul>
    </div>
{% endblock %}

{% block body %}
            {{ p_form.errors }}
    <div class="container">
    <div class="form">
        <h3>Add student and associate events.</h3>
        <form action="{% url 'add_profile' %}" name="form" id="form" method="post">
            {% csrf_token %}
            <input name="name" maxlength="500" required="" id="id_name" placeholder="Enter student name">
            <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Enter student email">
            <input type="tel" name="phone" maxlength="15" required="" id="id_phone" placeholder="Enter student phone number">
            <input name="college" maxlength="500" required="" id="id_college" placeholder="Enter student college name">
            <div class="select_events">
                <div class="event ">
                    <div class="heading">
                        <h5>Events</h5>
                        <input type="search" placeholder="Search Events" id="search-event">
                    </div>
                    <div class="options">
                        {% for event in event_list %}
                            <div class="item">
                                <div class="roundedOne">
                                    <input type="checkbox" name="{{ event.code }}" value="{{ event.name }}" id="{{ event.name }}" />
                                    <label for="{{ event.name }}"></label>
                                </div>
                                <label class="event-names" for="{{ event.name }}"><span>{{ event.name }}</span></label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="workshop ">
                <div class="heading">
                    <h5>Workshops</h5>
                    <input type="search" placeholder="Search Workshops" id="search-workshop">
                </div>
                <div class="options">
                {% for workshop in workshop_list %}
                    <div class="item">
                        <div class="roundedOne">
                            <input type="checkbox" name="{{ workshop.code }}" value="{{ workshop.code }}" id="{{ workshop.name }}" />
                            <label for="{{ workshop.name }}"></label>
                        </div>
                    <label class="workshop-names" for="{{ workshop.name }}"><span>{{ workshop.name }}</span></label>
                    </div>
                {% endfor %}
                </div>
            </div>
            </div>
        <input type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong" id="submit-true" value="Submit">
        </form>
    </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="content">
                    <div class="profile">
                        <h3>Profile details</h3>
                        <div class="name"> Name : <span id="name-confirm"></span></div>
                        <div class="email">Email : <span id="email-confirm"></span></div>
                        <div class="phone">Phone : <span id="phone-confirm"></span></div>
                        <div class="college">College : <span id="college-confirm"></span></div>

                    </div>
                    <div class="registered">
                        <h3>Registered for</h3>
                        <span id="event-confirm"></span>
                    </div>
              </div>
              <div class="modal-footer">
                <button class="btn btn-secondary" id="close-btn" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="submit-success">Go</button>
              </div>
            </div>
          </div>
        </div>
    </div>


{% endblock %}
{% block script %}
    <script>
        $(".item").click(function () {
            var elem = $("input[type=checkbox]");
            elem.each(function () {
                if($(this)[0].checked){
                    $($($(this)[0].parentElement)[0].parentElement)[0].style.backgroundColor = 'coral';
                }
                else{
                    $($($(this)[0].parentElement)[0].parentElement)[0].style.backgroundColor = 'white';

                }
            });
        });
        $('#search-event').keyup(function(){
           var valThis = $(this).val().toLowerCase();
            if(valThis === ""){
                $('.event > .options > .item').show();
            } else {
                $('.event > .options > .item').each(function(){
                    var text = $(this).text().toLowerCase();
                    (text.indexOf(valThis) >= 0) ? $(this).show() : $(this).hide();
                });
           }
        });
        $('#search-workshop').keyup(function(){
           var valThis = $(this).val().toLowerCase();
            if(valThis === ""){
                $('.workshop > .options > .item').show();
            } else {
                $('.workshop > .options > .item').each(function(){
                    var text = $(this).text().toLowerCase();
                    (text.indexOf(valThis) >= 0) ? $(this).show() : $(this).hide();
                });
           }
        });
        $('#submit-true').click(function () {
            $('#name-confirm').text($('#id_name').val());
            $('#email-confirm').text($('#id_email').val());
            $('#phone-confirm').text($('#id_phone').val());
            $('#college-confirm').text($('#id_college').val());
            $('#event-confirm').text("");
            var elem = $("input[type=checkbox]");
            elem.each(function () {
                if($(this)[0].checked){
{#                    console.log($(this));#}
{#                    console.log($(this)[0].defaultValue);#}
                    $('#event-confirm').append($(this)[0].id + "<br>");
                }
            });
        });
        $('#submit-success').click(function () {
            document.getElementById("form").submit();
            console.log("dfsd");
        });
        $('#search_dept').keyup(function () {
            var valThis = $("#search_dept").val().toLowerCase();
            console.log(valThis)
            if(valThis === ""){
                $('.event-table > tbody > tr ').show();
            } else {
                $('.event-table > tbody > tr').each(function(){
                    console.log("fsd")
                    var text = $(this).text().toLowerCase();
                    (text.indexOf(valThis) >= 0) ? $(this).show() : $(this).hide();
                });
           }
        });
        $('.event-info').click(function () {
            $('.container').fadeOut();
            $('.event-list').fadeIn();

            $('.nav-item').each(function () {
                $(this).removeClass(" active");
            });
            $($(this)[0].parentElement).addClass("  active");
        });
        $('.form-submit').click(function () {
            $('.event-list').fadeOut();
            $('.container').fadeIn();

            $('.nav-item').each(function () {
                $(this).removeClass(" active");
            });
            $($(this)[0].parentElement).addClass("  active");
        })
    </script>
{% endblock %}

EventManagement/templates/EventManagement/login.html
{% extends 'EventManagement/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'sign.css' %}">
{% endblock %}
{% block body %}
<div class="container">
    <form action="{% url 'login' %}" method="post" class="form" >
        {% csrf_token %}
        <h4>Enter your credentials</h4>
        <input type="text" name="username" placeholder="Enter your username" required>
        <input type="password" name="password" placeholder="Enter your password" required>
        <input type="submit">
    </form>
</div>
{% endblock %}
{% block script %}
    <script>
        $('.event-list')[0].style.display = 'none';
    </script>
{% endblock %}

EventManagement/templates/EventManagement/profile_add_sucess.html
success

EventManagement/templates/EventManagement/registration_email.html
Hi {{ profile.name }},<br>

<p>Welcome to Ritu'18.</p>

We hope you have a nice time :)<br>

Please find your QR code attached.<br>

Your ID is {{ profile.id_code }}

Team Ritu <br>

EventManagement/templates/EventManagement/sign_in.html
{% extends 'EventManagement/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'sign.css' %}">
{% endblock %}
{% block body %}
<div class="container">
    <form action="{% url 'login' %}" method="post" class="form" >
        {% csrf_token %}
        <h4>Enter your credentials</h4>
        <input type="text" name="username" placeholder="Enter your username" required>
        <input type="password" name="password" placeholder="Enter your password" required>
        <input type="submit">
    </form>
</div>
{% endblock %}

EventManagement/templates/EventManagement/update_event.html
{% extends 'EventManagement/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'update_event.css' %}">
{% endblock %}
{% block nav-icons %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Welcome {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
        </ul>
    </div>
{% endblock %}

{% block body %}
    <div class="errors">
        {{ form.errors }}
    </div>
    <div class="container">
    <form action="{%  url 'update_event' slug %}" method="post" class="form">
        <h3>Edit details of events:</h3>
        {% csrf_token %}
        <span>Event Name : </span><input type="text" name="name" value="{{ form.instance.name }}" maxlength="255" required="" disabled id="id_name">
        <span>Timing : </span><input type="text" name="timing" value="{{ form.instance.timing }}" maxlength="250" required="" id="id_timing">
        <span>Additional Info : </span><textarea name="additional_data" cols="70" rows="2" id="id_additional_data" placeholder="Eg: Event venue changed or Event prelims will start exactly at 11 etc.">{{ form.instance.additional_data }}</textarea>
        <span>Amount : </span><input type="text" name="amount" value="{{ form.instance.amount }}" maxlength="10" required=""  disabled id="id_amount">
        <span>Team Event? : <input type="checkbox" name="is_team_event" id="id_is_team_event"></span>
        <span>Enter Venue : </span><input type="text" name="venue" value="{{ form.instance.venue }}" maxlength="500" required="" id="id_venue" placeholder="Venue">
        <input type="submit">
    </form>
    </div>

    {{ form.EventForm.Event.name}}
{% endblock %}